---
title: "Expected Points Rushing Models"
author: "Joe Sydlowski"
date: Sys.Date()
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Libraries
library(catboost)
library(mgcv)

library(tidyverse)
library(tidymodels)
library(here)
library(arrow)
library(nflfastR)
library(stacks)
library(lubridate)
library(baguette)
library(rules)
library(doParallel)
library(treesnip)

library(finetune)
library(DALEXtra)
library(iBreakDown)


all_cores <- parallelly::availableCores() - 1
future::plan("multisession", workers = all_cores)

# memory.limit(size = 100000)

#Functions
get_age <- function(from_date,to_date = lubridate::now(),dec = FALSE){
  if(is.character(from_date)) from_date <- lubridate::as_date(from_date)
  if(is.character(to_date))   to_date   <- lubridate::as_date(to_date)
  if (dec) { age <- lubridate::interval(start = from_date, end = to_date)/(lubridate::days(365)+lubridate::hours(6))
  } else   { age <- lubridate::year(lubridate::as.period(lubridate::interval(start = from_date, end = to_date)))}
  round(age,2)
}
```

## Load the Data

```{r nflfastr}
start_year <- 2015

nflfastr_rosters <-
  nflfastR::fast_scraper_roster(start_year:2020) %>%
  select(season, gsis_id, position, full_name, birth_date, sportradar_id) %>% 
  mutate(position = dplyr::if_else(position %in% c("HB","FB"), "RB", position))

rush_df <-
  arrow::open_dataset("~/Documents/DynastyProcess/db/data/nflfastr_pbp") %>% 
  filter(season >= start_year) %>% 
  dplyr::collect() %>%
  filter(play_type == "run",
         !str_detect(desc, "kneel|Aborted")) %>%
  left_join(nflfastr_rosters, by = c("fantasy_player_id" = "gsis_id", "season")) %>%
  filter(position %in% c("QB","RB","WR","TE")) %>%
  mutate(game_month = month(game_date),
         game_month = if_else(game_month < 3, 12, game_month),
         game_week = week(game_date),
         game_week = if_else(game_week <= 30, 53, game_week),
         game_wday = as.character(wday(game_date, label = TRUE)),
         game_wday = case_when(game_wday %in% c("Tue","Wed","Fri","Sat") ~ "Other",
                               TRUE ~ game_wday),
         
         game_time = hour(hms(start_time)),
         drive_play_count = if_else(is.na(drive_play_count), 7, drive_play_count),

         rusher_age = get_age(birth_date, game_date, dec = TRUE),
         two_point_converted = case_when(two_point_conv_result == "success" ~ 1,
                                         is.na(two_point_conv_result) & str_detect(desc, "ATTEMPT SUCCEEDS") ~ 1,
                                         TRUE ~ 0),
         score = if_else(rush_touchdown == 1 | two_point_converted == 1, 1, 0),
         rushing_yards = case_when(is.na(rushing_yards) & two_point_attempt == 1 & two_point_converted == 1 ~ yardline_100,
                                   is.na(rushing_yards) & two_point_attempt == 1 & two_point_converted == 0 ~ 0 ,
                                   TRUE ~ rushing_yards),

         down = if_else(two_point_attempt == 1, 4, down),
         
         surface = if_else(surface == "grass", "grass", "turf"),
         
         run_location = case_when(!is.na(run_location) ~ run_location,
                                  str_detect(desc, " left") ~ "left",
                                  str_detect(desc, " right") ~ "right",
                                  str_detect(desc, " middle") ~ "middle",
                                  TRUE ~ "unk"),
         
         
         run_gap = case_when(!is.na(run_gap) ~ run_gap,
                             run_location == "middle" ~ "guard",
                             str_detect(desc, " end") ~ "end",
                             str_detect(desc, " tackle") ~ "tackle",
                             str_detect(desc, " guard") ~ "guard",
                             str_detect(desc, " middle") ~ "guard",
                             TRUE ~ "unk"),
         
         temp = case_when(roof %in% c("closed", "dome") ~ 68L,
                          is.na(temp) ~ 60L,
                          TRUE ~ temp),
         wind = case_when(roof %in% c("closed", "dome") ~ 0L,
                          is.na(wind) ~ 8L,
                          TRUE ~ wind),
         
         season = factor(season, levels = as.character(c(2001:2020)), ordered = TRUE),
         week = factor(week, levels = as.character(c(1:21)), ordered = TRUE),
         game_month = factor(game_month, levels = as.character(c(9:12)), ordered = TRUE),
         game_week = factor(game_week, levels = as.character(c(36:53)), ordered = TRUE),
         game_time = factor(game_time, levels = as.character(c(9:23)), ordered = TRUE),
         qtr = factor(qtr, levels = as.character(c(1:6)), ordered = TRUE),
         down = factor(down, levels = as.character(c(1:4)), ordered = TRUE),
         goal_to_go = factor(goal_to_go, levels = as.character(c(0,1)), ordered = TRUE),
         shotgun = factor(shotgun, levels = as.character(c(0,1)), ordered = TRUE),
         no_huddle = factor(no_huddle, levels = as.character(c(0,1)), ordered = TRUE),
         qb_dropback = factor(qb_dropback, levels = as.character(c(0,1)), ordered = TRUE),
         qb_scramble = factor(qb_scramble, levels = as.character(c(0,1)), ordered = TRUE),
         two_point_attempt = factor(two_point_attempt, levels = as.character(c(0,1)), ordered = TRUE),
         score = factor(score, levels = as.character(c(0,1)), ordered = TRUE),
         
         rushing_fantasy_points = 6*rush_touchdown  + 2*two_point_converted + 0.1*rushing_yards - 2*fumble_lost,
         
         run_gap_dir = paste(run_location, run_gap, sep = "_")) %>%
  
  filter(run_gap_dir %in% c("left_end", "left_tackle", "left_guard", "middle_guard",
                            "right_guard", "right_tackle", "right_end")) %>% 
  select(season,
         week,
         
         rushing_yards,
         score,
         
         # desc,
         # game_id,
         
         posteam_type,
         game_month,
         game_week,
         game_wday,
         game_half,
         run_location,
         run_gap,
         run_gap_dir,
         surface,
         wind,
         temp,
         roof,
         game_time,
         
         position,
         rusher_age,
         
         yardline_100,
         quarter_seconds_remaining,
         half_seconds_remaining,
         game_seconds_remaining,
         fixed_drive,
         drive_play_count,

         qtr,
         down,
         goal_to_go,
         ydstogo,
         shotgun,
         no_huddle,
         qb_dropback,
         qb_scramble,
         score_differential,
         ep,
         wp,
         vegas_wp,
         two_point_attempt,
         series,
         total_line
  )

```

## Train Test Split Data 

```{r}
set.seed(815)

rush_train <-
  rush_df %>%
  filter(season <= 2019)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)

rush_test <-
  rush_df %>%
  filter(season > 2019)

# training_resamples <- 
#   rush_train %>% 
#   nest(cols = -season) %>%
#   rolling_origin(
#     initial = 2,
#     assess = 1,
#     cumulative = FALSE)

```

# Tidymodels

```{r}
# Change Factors to numeric
rush_yards_recipe_norm <- 
  recipe(rushing_yards ~ ., data = rush_train) %>%
  step_rm(score) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_other(all_nominal_predictors(), threshold = tune())

rush_yards_recipe_decorr <- 
  recipe(rushing_yards ~ ., data = rush_train) %>%
  step_rm(score) %>% 
  step_impute_median(all_numeric_predictors()) %>% 
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors()) %>%
  step_corr(all_numeric_predictors(), threshold = tune())

# LASSO Regression
rush_yards_reg <- 
  linear_reg(mode = "regression",
             engine = "glmnet",
             penalty = tune(),
             mixture = tune())

#Generalized Additive Model 
rush_yards_gam <- 
  gen_additive_mod(mode = "regression",
                   select_features = TRUE,
                   adjust_deg_free = 1,
                   engine = "mgcv")

# MARS Regression
rush_yards_mars <- 
  mars(mode = "regression",
       engine = "earth",
       num_terms = tune(),
       prod_degree = tune(),
       prune_method = tune())

# Decision Tree
rush_yards_cart <- 
   decision_tree(mode = "regression",
                 engine = "rpart",
                 cost_complexity = tune(),
                 min_n = tune(),
                 tree_depth = tune())

# Boosted Decision Tree
rush_yards_boost <- 
   boost_tree(mode = "regression",
              engine = "catboost",
              mtry = tune(),  
              trees = 1000,
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              # loss_reduction = tune(), 
              # stop_iter = tune(),
              sample_size = 1)

temp <- rush_train %>% select(where(is.numeric), -rushing_yards) %>% colnames()

temp2 <- rush_train %>% select(where(is.factor)) %>% colnames()

temp3 <- paste("rushing_yards ~",
               paste('s(', temp, ')', sep = "", collapse = ' + '),
               '+',
               paste('', temp2, '', sep = "", collapse = ' + '))

# Workflow Sets
rush_workflowsets <-
  workflow_set(
    preproc = list(decorr = rush_yards_recipe_decorr,
                   normalized = rush_yards_recipe_norm,
                   decorr = rush_yards_recipe_decorr,
                   decorr = rush_yards_recipe_decorr,
                   decorr = rush_yards_recipe_decorr),
    models = list(lasso = rush_yards_reg,
                  gam = rush_yards_gam,
                  mars = rush_yards_mars,
                  cart = rush_yards_cart,
                  boost = rush_yards_boost),
    cross = FALSE)

# temp <- rush_workflowsets %>%
#      pull_workflow("normalized_gam") %>%
#      parameters()
# 
# temp$object

# Update thresholds
# for(id in rush_workflowsets %>% filter(str_detect(wflow_id, "decorr")) %>% pull(wflow_id)) {
#   new_param <-
#     sets_norm %>%
#     pull_workflow(id) %>%
#     parameters() %>% 
#     update(threshold = threshold(c(0.05,0.95)))
#   
#   rush_workflowsets <-
#     rush_workflowsets %>%
#     option_add(param_info = new_param, id = id)
# }

# Update tuning params
rush_workflowsets <-
  rush_workflowsets %>%
  option_add(param_info = rush_workflowsets %>%
               pull_workflow("decorr_lasso") %>%
               parameters() %>%
               update(mixture = mixture(range = c(0,1))),
             id = "decorr_lasso") %>%
  
  option_add(param_info = rush_workflowsets %>%
               pull_workflow("decorr_mars") %>%
               parameters() %>%
               update(num_terms = num_terms(range = c(2,38))),
             id = "decorr_mars") %>% 
  
  option_add(param_info = rush_workflowsets %>%
               pull_workflow("decorr_cart") %>%
               parameters() %>%
               update(min_n = min_n(range = c(2,500))),
             id = "decorr_cart") %>% 
  
  option_add(param_info =
               rush_workflowsets %>%
               pull_workflow("decorr_boost") %>%
               parameters() %>%
               update(mtry = mtry(range = c(1,50)),
                      min_n = min_n(range = c(2,500)),
                      learn_rate = learn_rate(range = c(-2.5, -0.5),trans = scales::log10_trans())),
             id = "decorr_boost")

add_gam_formula <- 
  function(info_obj){

    wflow_obj <- info_obj$workflow[[1]]

    info_obj$workflow[[1]] <-
      wflow_obj %>%
      update_model(extract_spec_parsnip(wflow_obj), formula = as.formula(temp3))
    
    return(info_obj)
  }

rush_workflowsets_temp <- 
  rush_workflowsets %>% 
  filter(wflow_id == "normalized_gam") %>% 
  mutate(info = map(info, ~add_gam_formula(.x)))

rush_workflowsets <- 
  rush_workflowsets %>% 
  filter(wflow_id != "normalized_gam") %>% 
  bind_rows(rush_workflowsets_temp)
  
# map(rush_workflowsets$option, ~ .x$param_info$object)

# Bayesian Tuning
ctrl_race <-
  control_bayes(
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE,
    verbose = TRUE,
    uncertain = 5,
    no_improve = 10,
    seed = 815,
    time_limit = 540
  )

res_grid <-
  rush_workflowsets %>%
  workflow_map(
    'tune_bayes',
    metrics = metric_set(rmse),
    resamples = training_resamples,
    iter = 100,
    initial = 10,
    control = ctrl_race,
    verbose = TRUE
  )

saveRDS(res_grid, "res_grid_20210808.RDS")

#Model Eval
res_grid_unnest2 <- 
  res_grid %>% 
  mutate(metrics = map(result, collect_metrics)) %>%
  unnest(metrics) %>% 
  select(-c(info, option, result))

autoplot(res_grid, 
         rank_metric = "rmse",
         metric = "rmse",
         select_best = FALSE) +
  theme_minimal()

autoplot(res_grid, id = "normalized_boost", metric = "rmse")

# Stacks
rush_yards_stack <-
  stacks() %>% 
  add_candidates(res_grid) %>%
  blend_predictions() %>% 
  fit_members()

saveRDS(butcher(rush_yards_stack), "rush_yards_stack.RDS")

train_preds <- 
  rush_test %>%
  select(rushing_yards) %>% 
  bind_cols(predict(rush_yards_stack, rush_test, members = TRUE))

model_evals <- 
  colnames(train_preds) %>%
  map_dfr(
    .f = rmse, 
    truth = rushing_yards, 
    data = train_preds
  ) %>%
  mutate(member = colnames(train_preds))

best_results <- 
  res_grid %>% 
  pull_workflow_set_result("decorr_boost") %>%
  collect_metrics() %>% 
  filter(.iter == 22) %>% 
  select(mtry, min_n, tree_depth, learn_rate, threshold, .config)

boosting_wf_final <- 
   res_grid %>% 
   pull_workflow("decorr_boost") %>% 
   finalize_workflow(best_results)
  
final_fit <- fit(boosting_wf_final, rush_train)

saveRDS(final_fit, "rush_yards_final.RDS")

rush_test <-
  rush_test %>% 
  bind_cols(predict(final_fit, rush_test)) %>% 
  rename(rushing_yards_exp = .pred)

rmse_vec(rush_test$rushing_yards_exp, rush_test$rushing_yards)

```

# What have I created??

```{r}
rush_yards_stack_butch <- stacks::butcher(rush_yards_stack, verbose = TRUE)
  
final_fit %>%
  vip::vip(geom = "point")

rush_yards_explainer <-
  explain_tidymodels(
    final_fit,
    data = dplyr::select(rush_train, -rushing_yards),
    y =  rush_train$rushing_yards)


plot(break_down(rush_yards_explainer, new_observation = rush_train %>% sample_n(1)))

plot(feature_importance(rush_yards_explainer))

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "ydstogo",
    groups = "shotgun"
  )

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "yardline_100"
  )

plot(pdp_time) + xlim(0,15)

```

# Predicting Rush TDs
```{r}
set.seed(815)

rush_train <-
  rush_train %>% 
  bind_cols(predict(final_fit, rush_train)) %>% 
  rename(rushing_yards_exp = .pred)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)
```


```{r}
# Change Factors to numeric
rush_td_recipe_norm <- 
  recipe(score ~ ., data = rush_train) %>%
  step_rm(rushing_yards) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_other(all_nominal_predictors(), threshold = tune())

rush_td_recipe_decorr <- 
  recipe(score ~ ., data = rush_train) %>%
  step_rm(rushing_yards) %>% 
  step_impute_median(all_numeric_predictors()) %>% 
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors()) %>%
  step_corr(all_numeric_predictors(), threshold = tune())

#Generalized Additive Model 
rush_td_gam <- 
  gen_additive_mod(mode = "classification",
                   select_features = TRUE,
                   adjust_deg_free = 1,
                   engine = "mgcv")

# MARS Regression
rush_td_mars <- 
  mars(mode = "classification",
       engine = "earth",
       num_terms = tune(),
       prod_degree = tune(),
       prune_method = tune())

# Decision Tree
rush_td_cart <- 
   decision_tree(mode = "classification",
                 engine = "rpart",
                 cost_complexity = tune(),
                 min_n = tune(),
                 tree_depth = tune())

# Boosted Decision Tree
rush_td_boost <- 
   boost_tree(mode = "classification",
              engine = "catboost",
              mtry = tune(),  
              trees = 1000,
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              # loss_reduction = tune(), 
              # stop_iter = tune(),
              sample_size = 1)

temp <- rush_train %>% select(where(is.numeric), -c(score, rushing_yards)) %>% colnames()

temp2 <- rush_train %>% select(where(is.factor), -c(score, rushing_yards)) %>% colnames()

temp3 <- paste("score ~",
               paste('s(', temp, ')', sep = "", collapse = ' + '),
               '+',
               paste('', temp2, '', sep = "", collapse = ' + '))

# Workflow Sets
rush_td_workflowsets <-
  workflow_set(
    preproc = list(normalized = rush_td_recipe_norm,
                   decorr = rush_td_recipe_decorr,
                   decorr = rush_td_recipe_decorr,
                   decorr = rush_td_recipe_decorr),
    models = list(gam = rush_td_gam,
                  mars = rush_td_mars,
                  cart = rush_td_cart,
                  boost = rush_td_boost),
    cross = FALSE)

# temp <- rush_workflowsets %>%
#      pull_workflow("normalized_gam") %>%
#      parameters()
# 
# temp$object

# Update thresholds
# for(id in rush_workflowsets %>% filter(str_detect(wflow_id, "decorr")) %>% pull(wflow_id)) {
#   new_param <-
#     sets_norm %>%
#     pull_workflow(id) %>%
#     parameters() %>% 
#     update(threshold = threshold(c(0.05,0.95)))
#   
#   rush_workflowsets <-
#     rush_workflowsets %>%
#     option_add(param_info = new_param, id = id)
# }

# Update tuning params
rush_td_workflowsets <-
  rush_td_workflowsets %>%

  option_add(param_info = rush_td_workflowsets %>%
               pull_workflow("decorr_mars") %>%
               parameters() %>%
               update(num_terms = num_terms(range = c(2,38))),
             id = "decorr_mars") %>% 
  
  option_add(param_info = rush_td_workflowsets %>%
               pull_workflow("decorr_cart") %>%
               parameters() %>%
               update(min_n = min_n(range = c(2,500))),
             id = "decorr_cart") %>% 
  
  option_add(param_info =
               rush_td_workflowsets %>%
               pull_workflow("decorr_boost") %>%
               parameters() %>%
               update(mtry = mtry(range = c(1,50)),
                      min_n = min_n(range = c(2,500)),
                      learn_rate = learn_rate(range = c(-2.5, -0.5),trans = scales::log10_trans())),
             id = "decorr_boost")

add_gam_formula <- 
  function(info_obj){

    wflow_obj <- info_obj$workflow[[1]]

    info_obj$workflow[[1]] <-
      wflow_obj %>%
      update_model(extract_spec_parsnip(wflow_obj), formula = as.formula(temp3))
    
    return(info_obj)
  }

rush_td_workflowsets_temp <- 
  rush_td_workflowsets %>% 
  filter(wflow_id == "normalized_gam") %>% 
  mutate(info = map(info, ~add_gam_formula(.x)))

rush_td_workflowsets <- 
  rush_td_workflowsets %>% 
  filter(wflow_id != "normalized_gam") %>% 
  bind_rows(rush_td_workflowsets_temp)
  
# map(rush_workflowsets$option, ~ .x$param_info$object)

# Bayesian Tuning
ctrl_race <-
  control_bayes(
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE,
    verbose = TRUE,
    uncertain = 5,
    no_improve = 10,
    seed = 815,
    time_limit = 600
  )

res_grid <-
  rush_td_workflowsets %>%
  workflow_map(
    'tune_bayes',
    metrics = metric_set(mn_log_loss),
    resamples = training_resamples,
    iter = 100,
    initial = 10,
    control = ctrl_race,
    verbose = TRUE
  )

saveRDS(res_grid, "res_grid_20210809.RDS")

#Model Eval
res_grid_unnest2 <- 
  res_grid %>% head(3) %>% 
  mutate(metrics = map(result, collect_metrics)) %>%
  unnest(metrics) %>% 
  select(-c(info, option, result))

autoplot(res_grid %>% head(3), 
         rank_metric = "mn_log_loss",
         metric = "mn_log_loss",
         select_best = FALSE) +
  theme_minimal()

autoplot(res_grid, id = "normalized_boost", metric = "mn_log_loss")

# Stacks
rush_td_stack <-
  stacks() %>% 
  add_candidates(res_grid %>% head(3)) %>%
  blend_predictions() %>% 
  fit_members()

saveRDS(butcher(rush_td_stack), "rush_td_stack.RDS")

train_preds <- 
  rush_test %>%
  select(score) %>% 
  bind_cols(predict(rush_td_stack, rush_test, members = TRUE, type = "prob"))

model_evals <- 
  colnames(train_preds) %>%
  map_dfr(
    .f = mn_log_loss, 
    truth = score, 
    data = train_preds
  ) %>%
  mutate(member = colnames(train_preds))

mn_log_loss_vec(train_preds$score, train_preds$.pred_0)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_mars_01_1)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_mars_09_1)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_mars_03_1)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_cart_08_1)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_boostIter2)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_boostIter12)
mn_log_loss_vec(train_preds$score, train_preds$.pred_0_decorr_boostIter14)

best_results <- 
  res_grid %>% 
  pull_workflow_set_result("decorr_boost") %>%
  collect_metrics() %>% 
  filter(.iter == 14) %>% 
  select(mtry, min_n, tree_depth, learn_rate, threshold, .config)

boosting_wf_final <- 
   res_grid %>% 
   pull_workflow("decorr_boost") %>% 
   finalize_workflow(best_results)
  
final_fit <- fit(boosting_wf_final, rush_train)

saveRDS(final_fit, "rush_td_final.RDS")

rush_test <-
  rush_test %>% 
  bind_cols(predict(final_fit, rush_test, type = "prob")) %>% 
  rename(rushing_td_exp = .pred_0)

mn_log_loss_vec(rush_test$score, rush_test$rushing_td_exp)

```


# What have I created??

```{r}
rush_yards_explainer <-
  explain_tidymodels(
    final_fit,
    data = dplyr::select(rush_train, -score),
    y =  rush_train$score)


plot(break_down(rush_yards_explainer, new_observation = rush_train %>% sample_n(1)))

plot(feature_importance(rush_yards_explainer))

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "rushing_yards_exp",
    groups = "yardline_100"
  )

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "yardline_100"
  )

plot(pdp_time) + xlim(0,15)

```
