---
title: "Expected Points Rushing Models"
author: "Joe Sydlowski"
date: "4/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Libraries
library(tidyverse)
library(tidymodels)
library(here)
library(arrow)
library(nflfastR)
library(stacks)
library(lubridate)
library(baguette)
library(rules)
library(doParallel)

all_cores <- parallel::detectCores(logical = FALSE)
doParallel::registerDoParallel(makePSOCKcluster(all_cores))
```


## Functions

```{r functions}
get_age <- function(from_date,to_date = lubridate::now(),dec = FALSE){
  if(is.character(from_date)) from_date <- lubridate::as_date(from_date)
  if(is.character(to_date))   to_date   <- lubridate::as_date(to_date)
  if (dec) { age <- lubridate::interval(start = from_date, end = to_date)/(lubridate::days(365)+lubridate::hours(6))
  } else   { age <- lubridate::year(lubridate::as.period(lubridate::interval(start = from_date, end = to_date)))}
  round(age,2)
}
```


## Load the Data

```{r nflfastr}

rolling_df <- 
  arrow::open_dataset("~/Documents/DynastyProcess/research/expected-points/data/rolling_df") %>% 
  dplyr::collect()

rushing_df <-
  arrow::open_dataset("~/Documents/DynastyProcess/db/data/nflfastr_pbp") %>% 
  filter(season >= 2007) %>% 
  dplyr::collect() %>%
  filter(play_type == "run",
         !str_detect(desc, "kneel|Aborted")) %>% 
  inner_join(rolling_df, by = c("fantasy_player_id"="gsis_id", "season", "week")) %>%
  filter(position %in% c("QB","RB","WR","TE")) %>%
  mutate(game_month = month(game_date),
         game_month = if_else(game_month < 3, 12, game_month),
         game_week = week(game_date),
         game_week = if_else(game_week <= 30, 53, game_week),
         game_wday = as.character(wday(game_date, label = TRUE)),
         game_wday = case_when(game_wday %in% c("Tue","Wed","Fri","Sat") ~ "Other",
                               TRUE ~ game_wday),
         
         rusher_age = get_age(birth_date, game_date, dec = TRUE),
         two_point_converted = case_when(two_point_conv_result == "success" ~ 1,
                                         is.na(two_point_conv_result) & str_detect(desc, "ATTEMPT SUCCEEDS") ~ 1,
                                         TRUE ~ 0),
         score = if_else(rush_touchdown == 1 | two_point_converted == 1, 1, 0),
         yards_gained = if_else(two_point_attempt == 1 & two_point_converted == 1, yardline_100, yards_gained),
         # yards_gained = log10(yards_gained),
         
         down = if_else(two_point_attempt == 1, 4, down),
         
         surface = if_else(surface == "grass", "grass", "turf"),
         
         run_location = case_when(!is.na(run_location) ~ run_location,
                                  str_detect(desc, " left") ~ "left",
                                  str_detect(desc, " right") ~ "right",
                                  str_detect(desc, " middle") ~ "middle",
                                  TRUE ~ "unk"),
         
         
         run_gap = case_when(!is.na(run_gap) ~ run_gap,
                             run_location == "middle" ~ "guard",
                             str_detect(desc, " end") ~ "end",
                             str_detect(desc, " tackle") ~ "tackle",
                             str_detect(desc, " guard") ~ "guard",
                             str_detect(desc, " middle") ~ "guard",
                             TRUE ~ "unk"),
         
         temp = case_when(roof %in% c("closed", "dome") ~ 68L,
                          is.na(temp) ~ 60L,
                          TRUE ~ temp),
         wind = case_when(roof %in% c("closed", "dome") ~ 0L,
                          is.na(wind) ~ 8L,
                          TRUE ~ wind),
         
         rushing_fantasy_points = 6*rush_touchdown  + 2*two_point_converted + 0.1*yards_gained - 2*fumble_lost,
         
         run_gap_dir = paste(run_location, run_gap, sep = "_")) %>%
  
  filter(run_gap_dir %in% c("left_end", "left_tackle", "left_guard", "middle_guard",
                            "right_guard", "right_tackle", "right_end")) %>% 
  select(season,
         week,
         
         # desc,
         # player_name,
         # posteam,
         
         posteam_type,
         game_month,
         game_week,
         game_wday,
         game_half,
         run_location,
         run_gap,
         run_gap_dir,
         surface,
         wind,
         temp,
         roof,
         # Active_Inactive,
         # Game_Designation,
         # Injury_Type,
         position,
         
         rusher_age,
         game_number,
         game_number_active,
         
         yards_gained,
         yardline_100,
         quarter_seconds_remaining,
         half_seconds_remaining,
         game_seconds_remaining,
         drive,
         drive_play_count,
         # drive_start_yard_line,
         
         qtr,
         down,
         goal_to_go,
         ydstogo,
         shotgun,
         no_huddle,
         qb_dropback,
         qb_scramble,
         score_differential,
         ep,
         wp,
         vegas_wp,
         two_point_attempt,
         series,
         total_line,
         
         contains("to_date"),
         contains("rolling16"),
         -contains("snap"),
         -contains("broken"),
         -contains("pass"),
         -contains("interceptions"),
         -contains("completions"),
         -contains("sack"),
         -contains("rec"),
         -starts_with("attempts")
  )

# rushing_df %>%
#   select(
#     contains("season_to_date")
# 
#   ) %>%
#   colnames()
#
# rushing_df %>% 
#   group_by(season) %>% 
#   summarise(across(.cols = contains("to_date"),
#                    .fns = mean)) %>% view()
# 
# rushing_df %>%
#   filter(drive_play_count > 0) %>% 
#   ggplot(aes(x = drive_play_count, y = yards_gained)) +
#   geom_point() +
#   geom_smooth()
# 
# rushing_df %>%
#   group_by(qb_dropback, position) %>%
#   summarise(n(), mean(yards_gained)) %>%
#   view()
# 
# rushing_df %>% 
#   filter(is.na(run_location)) %>%
#   view()
# 
# rushing_df %>% 
#   filter(run_location == "middle", run_gap == "end" ) %>%
#   # sample_n(30) %>% 
#   pull(desc)

rm(rolling_df)
```

## Train Test Split Data 

```{r}
rushing_train <-
  rushing_df %>%
  filter(season <= 2019)

training_resamples <- 
  rushing_train %>% 
  vfold_cv(v = 10)
  # nest(cols = -season) %>% 
  # rolling_origin(
  #   initial = 3,
  #   assess = 1,
  #   cumulative = FALSE) %>% 
  # mutate(splits = map(splits, ~unnest(.x$data, cols = c(cols))))

rushing_test <-
  rushing_df %>%
  filter(season > 2019)
```

# Tidymodels

```{r}
# set up a basic recipe
rushing_yards_recipe <- 
  recipe(yards_gained ~ ., data = rushing_train) %>%
  step_impute_median(all_numeric_predictors()) %>% 
  step_zv(all_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors(), one_hot = TRUE) %>% 
  step_pca(all_numeric_predictors(), num_comp = tune())

# LASSO Regression ran in less than 2 hours
set.seed(2005)

rushing_yards_reg <- 
  linear_reg(penalty = tune(), mixture = tune()) %>%
  set_engine("glmnet") %>%
  set_mode("regression")

rushing_yards_reg_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_reg)

rushing_yards_reg_res <- 
  tune_bayes(
    rushing_yards_reg_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_reg_wf %>% parameters() %>% update(num_comp = num_comp(c(0, 40))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Neural Net Regression
rushing_yards_nnet <- 
   mlp(hidden_units = tune(), penalty = tune(), epochs = tune()) %>% 
   set_engine("nnet", MaxNWts = 50000) %>% 
   set_mode("regression")

rushing_yards_nnet_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_nnet)

rushing_yards_nnet_res <- 
  tune_bayes(
    rushing_yards_nnet_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_nnet_wf %>% parameters() %>% update(hidden_units = hidden_units(c(1,27))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# KNN Regression
rushing_yards_knn <- 
  nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>%
  set_engine("kknn") %>%
  set_mode("regression")

rushing_yards_knn_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_knn)

rushing_yards_knn_res <- 
  tune_bayes(
    rushing_yards_knn_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Cubist Rules Regression
rushing_yards_cubist <- 
  cubist_rules(
    committees = tune(), 
    neighbors = tune()
  ) %>%
  set_engine("Cubist") %>%
  set_mode("regression")

rushing_yards_cubist_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_cubist)

rushing_yards_cubist_res <- 
  tune_bayes(
    rushing_yards_cubist_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# MARS Regression
all_cores <- parallel::detectCores(logical = FALSE)
doParallel::registerDoParallel(makePSOCKcluster(all_cores))

rushing_yards_mars <- 
  mars(prod_degree = tune()) %>%
  set_engine("earth") %>%
  set_mode("regression")

rushing_yards_mars_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_mars)

rushing_yards_mars_res <- 
  tune_bayes(
    rushing_yards_mars_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_mars_wf %>% parameters() %>% update(num_comp = num_comp(c(0, 40))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Bagged MARS Regression ran over 6 hours
rushing_yards_marsbag <- 
  bag_mars(prod_degree = tune()) %>%
  set_engine("earth", times = 50L) %>%
  set_mode("regression")

rushing_yards_marbag_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_marsbag)

rushing_yards_marsbag_res <- 
  tune_bayes(
    rushing_yards_marbag_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_marbag_wf %>% parameters() %>% update(num_comp = num_comp(c(0, 40))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Support Vector Regression Didn't finish overnight
rushing_yards_svm <- 
  svm_rbf(cost = tune(), rbf_sigma = tune()) %>%
  set_engine("kernlab") %>%
  set_mode("regression")

rushing_yards_svm_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_svm)

rushing_yards_svm_res <- 
  tune_bayes(
    rushing_yards_svm_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_svm_wf %>% parameters() %>% update(num_comp = num_comp(c(0, 40))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Decision Tree Ran in less than 2 hours
rushing_yards_cart <- 
   decision_tree(cost_complexity = tune(), min_n = tune(), tree_depth = tune()) %>% 
   set_engine("rpart") %>% 
   set_mode("regression")

rushing_yards_cart_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_cart)

rushing_yards_cart_res <- 
  tune_bayes(
    rushing_yards_cart_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_cart_wf %>% parameters() %>% update(num_comp = num_comp(c(0, 40))),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Random forest Ran for over 5 hours
rushing_yards_rand <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")

rushing_yards_rand_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_rand)

rushing_yards_rand_res <- 
  tune_bayes(
    rushing_yards_rand_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = 
      rushing_yards_rand_wf %>% 
      parameters() %>% 
      update(num_comp = num_comp(c(0, 40)),
             mtry = finalize(mtry(), rushing_train)),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Bagged Decision Tree
rushing_yards_bag <- 
   bag_tree(cost_complexity = tune(), tree_depth = tune(), min_n = tune(), class_cost = tune()) %>% 
   set_engine("rpart", times = 50L) %>% 
   set_mode("regression")

rushing_yards_bag_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_bag)

rushing_yards_bag_res <- 
  tune_bayes(
    rushing_yards_bag_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Boosted Decision Tree
rushing_yards_boost <- 
   boost_tree(tree_depth = tune(), learn_rate = tune(), loss_reduction = tune(), 
              min_n = tune(), sample_size = tune(), trees = 1000, mtry = tune()) %>% 
   set_engine("xgboost") %>% 
   set_mode("regression")

rushing_yards_boost_wf <- 
  workflow() %>% 
  add_recipe(rushing_yards_recipe) %>% 
  add_model(rushing_yards_boost)

rushing_yards_boost_res <- 
  tune_bayes(
    rushing_yards_boost_wf, 
    resamples = training_resamples,
    metrics = metric_set(rmse),
    param_info = rushing_yards_boost_wf %>% parameters() %>% update(mtry = finalize(mtry(), rushing_train)),
    initial = 10,
    iter = 10,
    control = control_bayes(verbose = TRUE, save_pred = TRUE, save_workflow = TRUE)
  )

# Metrics
# rushing_yards_reg_res %>% collect_metrics()
# 
# rushing_yards_reg_res %>%
#   collect_metrics() %>% 
#   select(mean, penalty, mixture, .metric) %>%
#   pivot_longer(penalty:mixture,
#                values_to = "value",
#                names_to = "parameter"
#   ) %>%
#   ggplot(aes(value, mean, color = parameter)) +
#   geom_point(alpha = 0.8, show.legend = FALSE) +
#   facet_wrap(~.metric, scales = "free_y") 
# 
final_rf <-
  finalize_workflow(
    rushing_yards_mars_wf,
    select_best(rushing_yards_mars_res, "rmse")
  )

rushyds_fit <- fit(final_rf, data = rushing_train)

pull_workflow_fit(rushyds_fit) %>%
  vip::vip(geom = "point")

```

## Ensemble

```{r}
rushing_yards_stack <- 
  stacks() %>%
  add_candidates(rushing_yards_reg_res) %>%
  add_candidates(rushing_yards_nnet_res) %>%
  add_candidates(rushing_yards_knn_res) %>%
  add_candidates(rushing_yards_cubist_res) %>%
  add_candidates(rushing_yards_mars_res) %>%
  add_candidates(rushing_yards_marbag_res) %>%
  add_candidates(rushing_yards_cart_res) %>%
  add_candidates(rushing_yards_rand_res) %>%
  add_candidates(rushing_yards_bag_res) %>%
  add_candidates(rushing_yards_boost_res) %>%
  blend_predictions() %>% 
  fit_members()

train_fits <- 
  rushing_train %>%
  bind_cols(predict(rushing_yards_stack, ., members = TRUE))

train_preds <- 
  rushing_train %>%
  select(yards_gained) %>% 
  bind_cols(predict(rushing_yards_stack, rushing_train, members = TRUE))

colnames(train_preds) %>%
  map_dfr(
    .f = rmse, 
    truth = yards_gained, 
    data = train_preds
  ) %>%
  mutate(member = colnames(train_preds))

train_preds %>% 
  summarise(across(.fns = list(mean, min, max),
                   .names = "{.col}_{.fn}")) %>% 
  pivot_longer(cols = everything())


```

