---
title: "Expected Points Rushing Models"
author: "Joe Sydlowski"
date: Sys.Date()
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Libraries
library(catboost)
library(mgcv)

library(tidyverse)
library(tidymodels)
library(here)
library(arrow)
library(nflfastR)
library(stacks)
library(lubridate)
library(baguette)
library(rules)
library(doParallel)
library(treesnip)

library(finetune)
library(DALEXtra)
library(iBreakDown)


all_cores <- parallelly::availableCores() - 1
future::plan("multisession", workers = all_cores)
options(tune.dark = TRUE)
# memory.limit(size = 100000)

setwd(here())

#Functions
get_age <- function(from_date,to_date = lubridate::now(),dec = FALSE){
  if(is.character(from_date)) from_date <- lubridate::as_date(from_date)
  if(is.character(to_date))   to_date   <- lubridate::as_date(to_date)
  if (dec) { age <- lubridate::interval(start = from_date, end = to_date)/(lubridate::days(365)+lubridate::hours(6))
  } else   { age <- lubridate::year(lubridate::as.period(lubridate::interval(start = from_date, end = to_date)))}
  round(age,2)
}
```

## Load the Data

```{r nflfastr}
start_year <- 2014

nflfastr_rosters <-
  nflfastR::fast_scraper_roster(start_year:2020) %>%
  select(season, gsis_id, position, full_name, birth_date, sportradar_id) %>% 
  mutate(position = dplyr::if_else(position %in% c("HB","FB"), "RB", position))

rush_df <-
  arrow::open_dataset("~/Documents/DynastyProcess/db/data/nflfastr_pbp") %>% 
  filter(season >= start_year) %>% 
  dplyr::collect() %>%
  filter(play_type == "run",
         !str_detect(desc, "kneel|Aborted")) %>%
  left_join(nflfastr_rosters, by = c("fantasy_player_id" = "gsis_id", "season"), na_matches = "never") %>%
  filter(position %in% c("QB","RB","WR","TE")) %>%
  mutate(game_month = month(game_date),
         game_month = if_else(game_month < 3, 12, game_month),
         game_week = week(game_date),
         game_week = if_else(game_week <= 30, 53, game_week),
         game_wday = as.character(wday(game_date, label = TRUE)),
         game_wday = case_when(game_wday %in% c("Tue","Wed","Fri","Sat") ~ "Other",
                               TRUE ~ game_wday),
         
         game_time = hour(hms(start_time)),
         implied_total = case_when(posteam_type == "away" & spread_line<=0 ~ (total_line+spread_line)/2 - spread_line,
                                   posteam_type == "away" & spread_line>0 ~ (total_line-spread_line)/2,
                                   posteam_type == "home" & spread_line>0 ~ (total_line+spread_line)/2 - spread_line,
                                   posteam_type == "home" & spread_line<=0 ~ (total_line-spread_line)/2),
         
         rusher_age = get_age(birth_date, game_date, dec = TRUE),
         
          #Two Point Conversion fixes
         two_point_converted = case_when(two_point_conv_result == "success" ~ 1,
                                         is.na(two_point_conv_result) & str_detect(desc, "ATTEMPT SUCCEEDS") ~ 1,
                                         TRUE ~ 0),
         score = if_else(rush_touchdown == 1 | two_point_converted == 1, 1, 0),
         rushing_yards = case_when(is.na(rushing_yards) & two_point_attempt == 1 & two_point_converted == 1 ~ yardline_100,
                                   is.na(rushing_yards) & two_point_attempt == 1 & two_point_converted == 0 ~ 0 ,
                                   TRUE ~ rushing_yards),
         down = if_else(two_point_attempt == 1, 4, down),
         
         surface = if_else(surface == "grass", "grass", "turf"),
         run_location = case_when(!is.na(run_location) ~ run_location,
                                  str_detect(desc, " left") ~ "left",
                                  str_detect(desc, " right") ~ "right",
                                  str_detect(desc, " middle") ~ "middle",
                                  TRUE ~ "unk"),
         run_gap = case_when(!is.na(run_gap) ~ run_gap,
                             run_location == "middle" ~ "guard",
                             str_detect(desc, " end") ~ "end",
                             str_detect(desc, " tackle") ~ "tackle",
                             str_detect(desc, " guard") ~ "guard",
                             str_detect(desc, " middle") ~ "guard",
                             TRUE ~ "unk"),
         temp = case_when(roof %in% c("closed", "dome") ~ 68L,
                          is.na(temp) ~ 60L,
                          TRUE ~ temp),
         wind = case_when(roof %in% c("closed", "dome") ~ 0L,
                          is.na(wind) ~ 8L,
                          TRUE ~ wind),
         
         rushing_fantasy_points = 6*rush_touchdown + 2*two_point_converted + 0.1*rushing_yards - 2*fumble_lost,
         
         season = factor(season, levels = as.character(c(2001:2020)), ordered = TRUE),
         week = factor(week, levels = as.character(c(1:21)), ordered = TRUE),
         game_month = factor(game_month, levels = as.character(c(9:12)), ordered = TRUE),
         game_week = factor(game_week, levels = as.character(c(36:53)), ordered = TRUE),
         game_time = factor(game_time, levels = as.character(c(9:23)), ordered = TRUE),
         qtr = factor(qtr, levels = as.character(c(1:6)), ordered = TRUE),
         down = factor(down, levels = as.character(c(1:4)), ordered = TRUE),
         
         goal_to_go = factor(goal_to_go, levels = as.character(c(0,1))),
         shotgun = factor(shotgun, levels = as.character(c(0,1))),
         no_huddle = factor(no_huddle, levels = as.character(c(0,1))),
         qb_dropback = factor(qb_dropback, levels = as.character(c(0,1))),
         qb_scramble = factor(qb_scramble, levels = as.character(c(0,1))),
         two_point_attempt = factor(two_point_attempt, levels = as.character(c(0,1))),
         score = factor(score, levels = as.character(c(0,1))),
         first_down = factor(first_down, levels = as.character(c(0,1))),
         # rushing_yards = factor(rushing_yards),
         
         run_gap_dir = paste(run_location, run_gap, sep = "_")) %>%
  
  filter(run_gap_dir %in% c("left_end", "left_tackle", "left_guard", "middle_guard",
                            "right_guard", "right_tackle", "right_end")) %>% 
  select(season,
         week,
         
         rushing_yards,
         score,
         first_down,
         rushing_fantasy_points,
         
         # desc,
         # game_id,
         # wp,
         # series,
         
         posteam_type,
         game_month,
         game_week,
         game_wday,
         game_half,
         run_location,
         run_gap,
         run_gap_dir,
         surface,
         wind,
         temp,
         roof,
         game_time,
         
         position,
         rusher_age,
         
         yardline_100,
         quarter_seconds_remaining,
         half_seconds_remaining,
         game_seconds_remaining,
         fixed_drive,
         
         qtr,
         down,
         goal_to_go,
         ydstogo,
         shotgun,
         no_huddle,
         qb_dropback,
         qb_scramble,
         score_differential,
         ep,
         vegas_wp,
         two_point_attempt,
         implied_total
  )

# corr_obj <- corrr::correlate(rush_df %>% select(where(is.numeric)))

```

## Train Test Split Data 
```{r}
set.seed(815)

rush_train <-
  rush_df %>%
  filter(season <= 2019)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)

rush_test <-
  rush_df %>%
  filter(season > 2019)

# training_resamples <- 
#   rush_train %>% 
#   nest(cols = -season) %>%
#   rolling_origin(
#     initial = 2,
#     assess = 1,
#     cumulative = FALSE)

```

# Rushing yards
```{r}

#Create recipe
rush_yards_recipe <- 
  recipe(rushing_yards ~ ., data = rush_train) %>%
  step_rm(c(score, first_down, rushing_fantasy_points)) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_unknown(all_nominal_predictors())

# prepped <- prep(rush_yards_recipe)
# juiced <- juice(prepped)

# Boosted Decision Tree
rush_yards_boost <- 
   boost_tree(mode = "regression",
              engine = "catboost",
              mtry = tune(),  
              trees = tune(),
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              sample_size = 1)

# Workflow Sets
rush_yards_wf <- workflow(rush_yards_recipe, rush_yards_boost)

new_params <- 
  parameters(rush_yards_wf) %>%
  update(mtry = mtry(range = c(1,35)),
         min_n = min_n(range = c(2,1000)),
         tree_depth = tree_depth(range = c(2,10)),
         learn_rate = learn_rate(range = c(-2.5, -0.5), trans = scales::log10_trans()))

# Bayesian Tuning
ctrl_bayes <-
  control_bayes(
    verbose = TRUE,
    no_improve = 20,
    uncertain = 10,
    seed = 815,
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE
  )

res_grid <-
  tune_bayes(
    rush_yards_wf,
    resamples = training_resamples,
    iter = 100,
    param_info = new_params,
    metrics = metric_set(rmse),
    initial = 10,
    control = ctrl_bayes
  )

saveRDS(res_grid, "../models/rush_yards_tune.RDS")

#Model Eval
res_grid_unnest <- 
  res_grid %>% 
  collect_metrics()

autoplot(res_grid, 
         rank_metric = "rmse",
         metric = "rmse",
         select_best = FALSE) +
  theme_minimal()

best_model <- 
  select_best(res_grid, metric = "rmse")

finalize_rush_yards <- 
  finalize_workflow(rush_yards_wf, best_model)

fit_rush_yards <- fit(finalize_rush_yards, rush_train)

rush_test <-
  rush_test %>% 
  bind_cols(predict(fit_rush_yards, rush_test)) %>% 
  rename(rushing_yards_exp = .pred)

rmse_vec(rush_test$rushing_yards_exp, rush_test$rushing_yards)

saveRDS(butcher(fit_rush_yards), "../models/fit_rush_yards.RDS")

rush_yards_explainer <-
  explain_tidymodels(
    fit_rush_yards,
    data = select(rush_train, -rushing_yards),
    y =  rush_train$rushing_yards)

plot(feature_importance(rush_yards_explainer))

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "rusher_age",
    groups = "position"
  )

plot(pdp_time)
  

```

# Predicting Rush TDs
```{r}
set.seed(815)

fit_rush_yards <- readRDS("../models/fit_rush_yards.RDS")

rush_train <-
  rush_train %>% 
  bind_cols(predict(fit_rush_yards, rush_train)) %>% 
  rename(rushing_yards_exp = .pred)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)

#Create recipe
rush_td_recipe <- 
  recipe(score ~ ., data = rush_train) %>%
  step_rm(c(rushing_yards, first_down, rushing_fantasy_points)) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_unknown(all_nominal_predictors())

# prepped <- prep(rush_yards_recipe)
# juiced <- juice(prepped)

# Boosted Decision Tree
rush_td_boost <- 
   boost_tree(mode = "classification",
              engine = "catboost",
              mtry = tune(),  
              trees = tune(),
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              sample_size = 1)

# Workflow Sets
rush_td_wf <- workflow(rush_td_recipe, rush_td_boost)

new_params <- 
  parameters(rush_td_wf) %>%
  update(mtry = mtry(range = c(1,36)),
         min_n = min_n(range = c(2,1000)),
         tree_depth = tree_depth(range = c(2,10)),
         learn_rate = learn_rate(range = c(-2.5, -0.5), trans = scales::log10_trans()))

# map(rush_workflowsets$option, ~ .x$param_info$object)

# Bayesian Tuning
ctrl_bayes <-
  control_bayes(
    verbose = TRUE,
    no_improve = 20,
    uncertain = 10,
    seed = 815,
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE
  )

rush_td_tune_bayes <-
  tune_bayes(
    rush_td_wf,
    resamples = training_resamples,
    iter = 100,
    param_info = new_params,
    metrics = metric_set(mn_log_loss),
    initial = 10,
    control = ctrl_bayes
  )

saveRDS(rush_td_tune_bayes, "../models/rush_td_tune.RDS")


#Model Eval
res_grid_unnest <- 
  rush_td_tune_bayes %>% 
  collect_metrics()

autoplot(rush_td_tune_bayes, 
         rank_metric = "mn_log_loss",
         metric = "mn_log_loss",
         select_best = FALSE) +
  theme_minimal()

best_model <- 
  select_best(rush_td_tune_bayes, metric = "mn_log_loss")

finalize_rush_td <- 
  finalize_workflow(rush_td_wf, best_model)

fit_rush_tds <- fit(finalize_rush_td, rush_train)

rush_test <-
  rush_test %>%
  bind_cols(predict(fit_rush_tds, rush_test, type = "prob")) %>%
  rename(rushing_td_exp = .pred_1) %>% 
  select(-.pred_0)

mn_log_loss_vec(rush_test$score, rush_test$rushing_td_exp)

saveRDS(butcher(fit_rush_tds), "../models/fit_rush_tds.RDS")

rush_yards_explainer <-
  explain_tidymodels(
    fit_rush_tds,
    data = select(rush_train, -score),
    y =  rush_train$score)

plot(feature_importance(rush_yards_explainer))

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "ydstogo",
    groups = "shotgun"
  )

pdp_time <- 
  model_profile(
    rush_yards_explainer,
    variables = "yardline_100"
  )

plot(pdp_time) + xlim(0,15)
```

# Predicting Rush FDs
```{r}
set.seed(815)

fit_rush_tds <- readRDS("../models/fit_rush_tds.RDS")

rush_train <-
  rush_train %>% 
  bind_cols(predict(fit_rush_tds, rush_train, type = "prob")) %>%
  rename(rushing_td_exp = .pred_1) %>% 
  select(-.pred_0)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)

#Create recipe
rush_fd_recipe <- 
  recipe(first_down ~ ., data = rush_train) %>%
  step_rm(c(rushing_yards, score, rushing_fantasy_points)) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_unknown(all_nominal_predictors())
 
# prepped <- prep(rush_fd_recipe)
# juiced <- juice(prepped)

# Boosted Decision Tree
rush_fd_boost <- 
   boost_tree(mode = "classification",
              engine = "catboost",
              mtry = tune(),  
              trees = tune(),
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              # loss_reduction = tune(), 
              # stop_iter = tune(),
              sample_size = 1)

# Workflow Sets
rush_fd_wf <- workflow(rush_fd_recipe, rush_fd_boost)

new_params <- 
  parameters(rush_fd_wf) %>%
  update(mtry = mtry(range = c(1,37)),
         min_n = min_n(range = c(2,1000)),
         tree_depth = tree_depth(range = c(2,10)),
         learn_rate = learn_rate(range = c(-2.5, -0.5), trans = scales::log10_trans()))

# map(rush_workflowsets$option, ~ .x$param_info$object)

# Bayesian Tuning
ctrl_bayes <-
  control_bayes(
    verbose = TRUE,
    no_improve = 20,
    uncertain = 10,
    seed = 815,
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE
  )

rush_fd_tune_bayes <-
  tune_bayes(
    rush_fd_wf,
    resamples = training_resamples,
    iter = 100,
    param_info = new_params,
    metrics = metric_set(mn_log_loss),
    initial = 10,
    control = ctrl_bayes
  )

saveRDS(rush_fd_tune_bayes, "../models/rush_fd_tune.RDS")

#Model Eval
res_grid_unnest <- 
  rush_fd_tune_bayes %>% 
  collect_metrics()

autoplot(rush_fd_tune_bayes, 
         rank_metric = "mn_log_loss",
         metric = "mn_log_loss",
         select_best = FALSE) +
  theme_minimal()

best_model <- 
  select_best(rush_fd_tune_bayes, metric = "mn_log_loss")

finalize_rush_fd <- 
  finalize_workflow(rush_fd_wf, best_model)

fit_rush_fds <- fit(finalize_rush_fd, rush_train)

rush_test <-
  rush_test %>%
  bind_cols(predict(fit_rush_fds, rush_test, type = "prob")) %>%
  rename(rushing_fd_exp = .pred_1) %>% 
  select(-.pred_0)

mn_log_loss_vec(rush_test$first_down, rush_test$rushing_fd_exp)

saveRDS(butcher(fit_rush_fds), "../models/fit_rush_fds.RDS")
```

# Predicting Rush FPs
# Just use a linear fit
```{r}
set.seed(815)

fit_rush_fds <- readRDS("../models/fit_rush_fds.RDS")

rush_train <-
  rush_train %>% 
  bind_cols(predict(fit_rush_fds, rush_train, type = "prob")) %>%
  rename(rushing_fd_exp = .pred_1) %>% 
  select(-.pred_0)

training_resamples <-
  rush_train %>%
  vfold_cv(v = 5)

#Create recipe
rush_fp_recipe <- 
  recipe(rushing_fantasy_points ~ ., data = rush_train) %>%
  step_rm(c(rushing_yards, score, first_down)) %>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_unknown(all_nominal_predictors())
 
# prepped <- prep(rush_fd_recipe)
# juiced <- juice(prepped)

# Boosted Decision Tree
rush_fp_boost <- 
   boost_tree(mode = "regression",
              engine = "catboost",
              mtry = tune(),  
              trees = tune(),
              min_n = tune(),
              tree_depth = tune(),
              learn_rate = tune(),
              # loss_reduction = tune(), 
              # stop_iter = tune(),
              sample_size = 1)

# Workflow Sets
rush_fp_wf <- workflow(rush_fp_recipe, rush_fp_boost)

new_params <- 
  parameters(rush_fp_wf) %>%
  update(mtry = mtry(range = c(1,39)),
         min_n = min_n(range = c(2,500)),
         tree_depth = tree_depth(range = c(2,10)),
         learn_rate = learn_rate(range = c(-2.5, -0.5), trans = scales::log10_trans()))

# map(rush_workflowsets$option, ~ .x$param_info$object)

# Bayesian Tuning
ctrl_bayes <-
  control_bayes(
    verbose = TRUE,
    no_improve = 15,
    uncertain = 5,
    seed = 815,
    save_pred = TRUE,
    parallel_over = 'everything',
    save_workflow = TRUE
  )

rush_fp_tune_bayes <-
  tune_bayes(
    rush_fp_wf,
    resamples = training_resamples,
    iter = 50,
    param_info = new_params,
    metrics = metric_set(rmse),
    initial = 20,
    control = ctrl_bayes
  )

#Model Eval
res_grid_unnest <- 
  rush_fp_tune_bayes %>% 
  collect_metrics()

autoplot(rush_fp_tune_bayes, 
         rank_metric = "rmse",
         metric = "rmse",
         select_best = FALSE) +
  theme_minimal()

best_model <- 
  select_best(rush_fp_tune_bayes, metric = "rmse")

finalize_rush_fp <- 
  finalize_workflow(rush_fp_wf, best_model)

fit_rush_fps <- fit(finalize_rush_fp, rush_train)

rush_test <-
  rush_test %>%
  bind_cols(predict(fit_rush_fps, rush_test)) %>%
  rename(rushing_fp_exp = .pred) %>% 
  mutate(rushing_fp_exp_raw = if_else(two_point_attempt == 1, 2*rushing_td_exp, 6*rushing_td_exp) + 0.1*rushing_yards_exp,
         rushing_fp_exp_raw2 = if_else(two_point_attempt == 1, 2*rushing_td_exp, 6*rushing_td_exp) + 0.1*rushing_yards_exp - 0.01)

lm1 <- lm(rushing_fantasy_points ~ rushing_yards_exp + rushing_td_exp + two_point_attempt, data = rush_train)

rush_test <- 
  rush_test %>% 
  mutate(rushing_fp_exp_lm = predict(lm1, rush_test))

rush_test <- 
  rush_test %>% 
  mutate(rushing_fp_exp_raw2 = if_else(two_point_attempt == 1, 2*rushing_td_exp, 6*rushing_td_exp) + 0.1*rushing_yards_exp - 0.01)

rmse_vec(rush_test$rushing_fantasy_points, rush_test$rushing_fp_exp)
rmse_vec(rush_test$rushing_fantasy_points, rush_test$rushing_fp_exp_raw)
rmse_vec(rush_test$rushing_fantasy_points, rush_test$rushing_fp_exp_raw2)
rmse_vec(rush_test$rushing_fantasy_points, rush_test$rushing_fp_exp_lm)

saveRDS(butcher(fit_rush_fps), "../models/fit_rush_fps.RDS")

rush_fps_explainer <-
  explain_tidymodels(
    fit_rush_fps,
    data = select(rush_train, -rushing_fantasy_points),
    y =  rush_train$rushing_fantasy_points)

plot(feature_importance(rush_fps_explainer))

plot(break_down(rush_fps_explainer, new_observation = rush_train %>% sample_n(1)))

plot(model_profile(
    rush_fps_explainer,
    variables = "rushing_yards_exp"))
```
